import os
# COMPUTER_NAME = os.environ['COMPUTERNAME']
# print("Computer: ", COMPUTER_NAME)

WORKER_POOL_SIZE = 4

TARGET_VOXEL_MM = 1.00
MEAN_PIXEL_VALUE_NODULE = 41
LUNA_SUBSET_START_INDEX = 0

BASE_DIR_SSD = "./data/"
BASE_DIR = "./data/"
EXTRA_DATA_DIR = "resources/"
LUNA16_RAW_SRC_DIR = BASE_DIR + "luna/"
LUNA16_EXTRACTED_IMAGE_DIR = BASE_DIR_SSD + "luna16_extracted_images/"


